// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AButton: typeof import("ant-design-vue/es")["Button"];
    ACard: typeof import("ant-design-vue/es")["Card"];
    ACardMeta: typeof import("ant-design-vue/es")["CardMeta"];
    ACol: typeof import("ant-design-vue/es")["Col"];
    ActionsPane: typeof import("./src/components/organisms/ActionsPane/ActionsPane.vue")["default"];
    ALayout: typeof import("ant-design-vue/es")["Layout"];
    ALayoutContent: typeof import("ant-design-vue/es")["LayoutContent"];
    ALayoutSider: typeof import("ant-design-vue/es")["LayoutSider"];
    AMenu: typeof import("ant-design-vue/es")["Menu"];
    AMenuItem: typeof import("ant-design-vue/es")["MenuItem"];
    APageHeader: typeof import("ant-design-vue/es")["PageHeader"];
    AppBar: typeof import("./src/components/molecules/AppBar/AppBar.vue")["default"];
    AppLayout: typeof import("./src/components/organisms/AppLayout/AppLayout.vue")["default"];
    AppSideBar: typeof import("./src/components/molecules/AppSideBar/AppSideBar.vue")["default"];
    ARow: typeof import("ant-design-vue/es")["Row"];
    ASpace: typeof import("ant-design-vue/es")["Space"];
    ASpin: typeof import("ant-design-vue/es")["Spin"];
    ASubMenu: typeof import("ant-design-vue/es")["SubMenu"];
    ATooltip: typeof import("ant-design-vue/es")["Tooltip"];
    ATypographyTitle: typeof import("ant-design-vue/es")["TypographyTitle"];
    EditorInput: typeof import("./src/components/atoms/EditorInput/EditorInput.vue")["default"];
    EditorPane: typeof import("./src/components/organisms/EditorPane/EditorPane.vue")["default"];
    FilterInput: typeof import("./src/components/atoms/FilterInput/FilterInput.vue")["default"];
    FilterSort: typeof import("./src/components/molecules/FilterSort/FilterSort.vue")["default"];
    FilterSortList: typeof import("./src/components/molecules/FilterSortList/FilterSortList.vue")["default"];
    FilterSortSelect: typeof import("./src/components/atoms/FilterSortSelect/FilterSortSelect.vue")["default"];
    FiltersPane: typeof import("./src/components/organisms/FiltersPane/FiltersPane.vue")["default"];
    ResultPane: typeof import("./src/components/organisms/ResultPane/ResultPane.vue")["default"];
    ResultTable: typeof import("./src/components/atoms/ResultTable/ResultTable.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SortInput: typeof import("./src/components/atoms/SortInput/SortInput.vue")["default"];
  }
}
